version: "3.8"

services:
  ponder-db:
    image: postgres:15
    container_name: ponder-db-container
    environment:
      POSTGRES_DB: ponder_db
      POSTGRES_USER: ponder_user
      POSTGRES_PASSWORD: ponder_password
    ports:
      - "5432:5432"
    volumes:
      - ponder_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ponder_db_data:
