name: Release Avail Indexer

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'avail-indexer-v*.*.*'
      - 'avail-indexer-v*.*.*-*'

jobs:
  docker_build_push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#avail-indexer-}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_USER_EMAIL }}
          password: ${{ secrets.DO_USER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./avail
          file: ./avail/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            registry.digitalocean.com/availj/avail-indexer:${{ steps.version.outputs.version }}
            registry.digitalocean.com/availj/avail-indexer:latest
          cache-from: |
            type=gha,scope=avail-indexer
            type=registry,ref=registry.digitalocean.com/availj/avail-indexer:buildcache
          cache-to: |
            type=gha,scope=avail-indexer,mode=max
            type=registry,ref=registry.digitalocean.com/availj/avail-indexer:buildcache,mode=max
